# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    acme_api.event.jwt_created_listener:
            class: AppBundle\EventListener\JWTCreatedListener
            arguments: [ '@request_stack' ]
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    app.exception_listener:
            class: AppBundle\EventListener\ExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception }
    api_auth:
            class: AppBundle\Security\Authenticator
            arguments:
                - "@security.encoder_factory"
                - "@tactician.commandbus"
