version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/application
    restart: always
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: <%=props.dbPassword%>
      POSTGRES_USER: <%=props.dbUser%>
      POSTGRES_DB: <%=props.dbName%>
    ports:
       - <%=props.dbPort%>:1433
    volumes:
      - ./database/:/var/lib/postgresql
    restart: always
networks:
  default:
    driver: bridge