version: '3.1'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/api
      - ./docker/php_config/php.ini:/usr/local/etc/php/conf.d/php-extras.ini
      - ./docker/apache_config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/log:/var/log
    restart: always
  db:
    container_name: db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: <%=props.dbPassword%>
      POSTGRES_USER: <%=props.dbUser%>
      POSTGRES_DB: <%=props.dbName%>
    ports:
       - <%=props.dbPort%>:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    restart: always
networks:
  default:
    driver: bridge
