version: '3.1'
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/api
    restart: always
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: <%=props.dbPassword%>
      POSTGRES_USER: <%=props.dbUser%>
      POSTGRES_DB: <%=props.dbName%>
    ports:
       - <%=props.dbPort%>:5432
    volumes:
      - ./database/:/var/lib/postgresql
    restart: always
networks:
  default:
    driver: bridge