version: '3.1'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/api
      - ./docker/php_config/php.ini:/usr/local/etc/php/conf.d/php-extras.ini
      - ./docker/apache_config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/log:/var/log
    restart: always
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <%=props.dbPassword%>
      MYSQL_DATABASE: <%=props.dbName%>
      MYSQL_USER: <%=props.dbUser%>
    restart: always
    ports:
      - <%=props.dbPort%>:3306
    volumes:
      - ./database/:/var/lib/mysql
networks:
  default:
    driver: bridge