version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    restart: always
  composer:
    image: composer/composer:php7
    command: install
    volumes:
       - ./:/var/www/html
    restart: 'no'
  db:
    image: oracle
    environment:
      #MYSQL_ROOT_PASSWORD: mysql
    restart: always
    ports:
      - <%=props.dbPort%>:1521
    volumes:
      - ./database/:/opt/oracle/oradata
networks:
  default:
    driver: bridge