version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/application
    restart: always
  db:
    image: oracle
    environment:
      #MYSQL_ROOT_PASSWORD: mysql
    restart: always
    ports:
      - <%=props.dbPort%>:1521
    volumes:
      - ./database/:/opt/oracle/oradata
networks:
  default:
    driver: bridge